<?php

namespace ContainerMdCpDrl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContainerBuilderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.NwmT2jN.Symfony\Component\DependencyInjection\ContainerBuilder' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ContainerBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.NwmT2jN": it references class "Symfony\\Component\\DependencyInjection\\ContainerBuilder" but no such service exists.');
    }
}
