<?php

namespace Container1r7vy1c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DKkVCQ6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dKkVCQ6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dKkVCQ6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Repository\\UserRepository::matching' => ['privates', '.service_locator.tWJk8w6.App\\Repository\\UserRepository::matching()', 'getUserRepositorymatchingService', true],
            'App\\ex01\\ex01::build' => ['privates', '.service_locator.NwmT2jN.App\\ex01\\ex01::build()', 'getEx01buildService', true],
            'App\\ex01\\ex01::registerCommands' => ['privates', '.service_locator.JxCcp1M.App\\ex01\\ex01::registerCommands()', 'getEx01registerCommandsService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Repository\\UserRepository:matching' => ['privates', '.service_locator.tWJk8w6.App\\Repository\\UserRepository::matching()', 'getUserRepositorymatchingService', true],
            'App\\ex01\\ex01:build' => ['privates', '.service_locator.NwmT2jN.App\\ex01\\ex01::build()', 'getEx01buildService', true],
            'App\\ex01\\ex01:registerCommands' => ['privates', '.service_locator.JxCcp1M.App\\ex01\\ex01::registerCommands()', 'getEx01registerCommandsService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Repository\\UserRepository::matching' => '?',
            'App\\ex01\\ex01::build' => '?',
            'App\\ex01\\ex01::registerCommands' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Repository\\UserRepository:matching' => '?',
            'App\\ex01\\ex01:build' => '?',
            'App\\ex01\\ex01:registerCommands' => '?',
        ]);
    }
}
