<?php

namespace Container1r7vy1c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApplicationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.JxCcp1M.Symfony\Component\Console\Application' shared service.
     *
     * @return \Symfony\Component\Console\Application
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.JxCcp1M": it references class "Symfony\\Component\\Console\\Application" but no such service exists. You should maybe alias this class to the existing "console.messenger.application" service.');
    }
}
