<?php

namespace Container1r7vy1c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCriteriaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.tWJk8w6.Doctrine\Common\Collections\Criteria' shared service.
     *
     * @return \Doctrine\Common\Collections\Criteria
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.tWJk8w6": it references class "Doctrine\\Common\\Collections\\Criteria" but no such service exists.');
    }
}
