controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
e00_firstpage:
    path: /e00/firstpage
    controller: App\E00Bundle\Controller\E00Controller::firstPage
