<?php

namespace ContainerWSXwAvh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEx00createTableService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ertAJK0.App\ex00\Controller\ex00::createTable()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ertAJK0.App\\ex00\\Controller\\ex00::createTable()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'connection' => ['services', 'doctrine.dbal.default_connection', 'getDoctrine_Dbal_DefaultConnectionService', false],
        ], [
            'connection' => '?',
        ]))->withContext('App\\ex00\\Controller\\ex00::createTable()', $container);
    }
}
