<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIFRiWHu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIFRiWHu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIFRiWHu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIFRiWHu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIFRiWHu\App_KernelDevDebugContainer([
    'container.build_hash' => 'IFRiWHu',
    'container.build_id' => 'dbd08fcb',
    'container.build_time' => 1721308663,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIFRiWHu');
