<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container37qXaoK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container37qXaoK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container37qXaoK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container37qXaoK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container37qXaoK\App_KernelDevDebugContainer([
    'container.build_hash' => '37qXaoK',
    'container.build_id' => '556e0b7b',
    'container.build_time' => 1721295976,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container37qXaoK');
