<?php

namespace ContainerY0vcCur;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DbDeYe7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dbDeYe7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dbDeYe7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'view' => ['privates', '.errored..service_locator.dbDeYe7.Symfony\\Component\\Form\\FormView', NULL, 'Cannot autowire service ".service_locator.dbDeYe7": it references class "Symfony\\Component\\Form\\FormView" but no such service exists.'],
            'form' => ['privates', '.errored..service_locator.dbDeYe7.Symfony\\Component\\Form\\FormInterface', NULL, 'Cannot autowire service ".service_locator.dbDeYe7": it references interface "Symfony\\Component\\Form\\FormInterface" but no such service exists. Did you create a class that implements this interface?'],
        ], [
            'view' => 'Symfony\\Component\\Form\\FormView',
            'form' => 'Symfony\\Component\\Form\\FormInterface',
        ]);
    }
}
