<?php

namespace ContainerY0vcCur;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_D1iA6IJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.D1iA6IJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.D1iA6IJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\ex02\\Form\\UserType::buildForm' => ['privates', '.service_locator.AjyxovK.App\\ex02\\Form\\UserType::buildForm()', 'getUserTypebuildFormService', true],
            'App\\ex02\\Form\\UserType::configureOptions' => ['privates', '.service_locator.CDiLWep.App\\ex02\\Form\\UserType::configureOptions()', 'getUserTypeconfigureOptionsService', true],
            'App\\ex02\\Form\\UserType::buildView' => ['privates', '.service_locator.dbDeYe7.App\\ex02\\Form\\UserType::buildView()', 'getUserTypebuildViewService', true],
            'App\\ex02\\Form\\UserType::finishView' => ['privates', '.service_locator.dbDeYe7.App\\ex02\\Form\\UserType::finishView()', 'getUserTypefinishViewService', true],
            'App\\ex02\\ex02::build' => ['privates', '.service_locator.NwmT2jN.App\\ex02\\ex02::build()', 'getEx02buildService', true],
            'App\\ex02\\ex02::registerCommands' => ['privates', '.service_locator.JxCcp1M.App\\ex02\\ex02::registerCommands()', 'getEx02registerCommandsService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\ex02\\Form\\UserType:buildForm' => ['privates', '.service_locator.AjyxovK.App\\ex02\\Form\\UserType::buildForm()', 'getUserTypebuildFormService', true],
            'App\\ex02\\Form\\UserType:configureOptions' => ['privates', '.service_locator.CDiLWep.App\\ex02\\Form\\UserType::configureOptions()', 'getUserTypeconfigureOptionsService', true],
            'App\\ex02\\Form\\UserType:buildView' => ['privates', '.service_locator.dbDeYe7.App\\ex02\\Form\\UserType::buildView()', 'getUserTypebuildViewService', true],
            'App\\ex02\\Form\\UserType:finishView' => ['privates', '.service_locator.dbDeYe7.App\\ex02\\Form\\UserType::finishView()', 'getUserTypefinishViewService', true],
            'App\\ex02\\ex02:build' => ['privates', '.service_locator.NwmT2jN.App\\ex02\\ex02::build()', 'getEx02buildService', true],
            'App\\ex02\\ex02:registerCommands' => ['privates', '.service_locator.JxCcp1M.App\\ex02\\ex02::registerCommands()', 'getEx02registerCommandsService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\ex02\\Form\\UserType::buildForm' => '?',
            'App\\ex02\\Form\\UserType::configureOptions' => '?',
            'App\\ex02\\Form\\UserType::buildView' => '?',
            'App\\ex02\\Form\\UserType::finishView' => '?',
            'App\\ex02\\ex02::build' => '?',
            'App\\ex02\\ex02::registerCommands' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\ex02\\Form\\UserType:buildForm' => '?',
            'App\\ex02\\Form\\UserType:configureOptions' => '?',
            'App\\ex02\\Form\\UserType:buildView' => '?',
            'App\\ex02\\Form\\UserType:finishView' => '?',
            'App\\ex02\\ex02:build' => '?',
            'App\\ex02\\ex02:registerCommands' => '?',
        ]);
    }
}
