<?php

namespace ContainerY0vcCur;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEx02registerCommandsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JxCcp1M.App\ex02\ex02::registerCommands()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JxCcp1M.App\\ex02\\ex02::registerCommands()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'application' => ['privates', '.errored..service_locator.JxCcp1M.Symfony\\Component\\Console\\Application', NULL, 'Cannot autowire service ".service_locator.JxCcp1M": it references class "Symfony\\Component\\Console\\Application" but no such service exists. You should maybe alias this class to the existing "console.messenger.application" service.'],
        ], [
            'application' => 'Symfony\\Component\\Console\\Application',
        ]))->withContext('App\\ex02\\ex02::registerCommands()', $container);
    }
}
