<?php

namespace ContainerY0vcCur;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormViewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.dbDeYe7.Symfony\Component\Form\FormView' shared service.
     *
     * @return \Symfony\Component\Form\FormView
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.dbDeYe7": it references class "Symfony\\Component\\Form\\FormView" but no such service exists.');
    }
}
