<?php

namespace ContainerY0vcCur;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOptionsResolverService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.CDiLWep.Symfony\Component\OptionsResolver\OptionsResolver' shared service.
     *
     * @return \Symfony\Component\OptionsResolver\OptionsResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.CDiLWep": it references class "Symfony\\Component\\OptionsResolver\\OptionsResolver" but no such service exists.');
    }
}
