<?php

namespace ContainerY0vcCur;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserTypebuildFormService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AjyxovK.App\ex02\Form\UserType::buildForm()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AjyxovK.App\\ex02\\Form\\UserType::buildForm()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'builder' => ['privates', '.errored..service_locator.AjyxovK.Symfony\\Component\\Form\\FormBuilderInterface', NULL, 'Cannot autowire service ".service_locator.AjyxovK": it references interface "Symfony\\Component\\Form\\FormBuilderInterface" but no such service exists. Did you create a class that implements this interface?'],
        ], [
            'builder' => 'Symfony\\Component\\Form\\FormBuilderInterface',
        ]))->withContext('App\\ex02\\Form\\UserType::buildForm()', $container);
    }
}
