<?php

namespace ContainerY0vcCur;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserTypebuildViewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dbDeYe7.App\ex02\Form\UserType::buildView()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dbDeYe7.App\\ex02\\Form\\UserType::buildView()'] = ($container->privates['.service_locator.dbDeYe7'] ?? $container->load('get_ServiceLocator_DbDeYe7Service'))->withContext('App\\ex02\\Form\\UserType::buildView()', $container);
    }
}
