<?php

namespace Container5LVaa8S;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_OP6wQceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.OP6wQce' shared service.
     *
     * @return \App\ex02\Controller\Request
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\ex02\\Controller\\ex02::showForm()": the $request argument is type-hinted with the non-existent class or interface: "App\\ex02\\Controller\\Request". Did you forget to add a use statement?');
    }
}
