<?php

namespace ContainerO6k3yqM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEx012Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\ex01\ex01' shared autowired service.
     *
     * @return \App\ex01\ex01
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Bundle/BundleInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Bundle/Bundle.php';
        include_once \dirname(__DIR__, 4).'/src/ex01/ex01.php';

        return $container->services['App\\ex01\\ex01'] = new \App\ex01\ex01();
    }
}
